server:
  port: 19000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway-api
  cloud:
    consul:
      enabled: true
      host: 129.159.67.152
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        preferIpAddress: true

    gateway:
      routes:      
        - id: evaluacion-docente-api
          uri: lb://evaluacion-docente-api
          predicates:
            - Path=/evaluacion-docente-api/**
          filters:
            - RewritePath=/evaluacion-docente-api/(?<path>.*), /$\{path}
        - id: jsonplaceholder
          uri: https://jsonplaceholder.typicode.com/todos/1
          predicates:
            - Path=/todos/**
        - id: httpbin
          uri: http://httpbin.org:80
          predicates:
            - Path=/get/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
          
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"          

springdoc:
  show-actuator: false
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operations-sorter: method
    tags-sorter: alpha
    docExpansion: none
    
    
